import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "@/context/UserContext";
import { TanstackProvider } from "@/components/providers/tanstack-provider";

const unbounded = Unbounded({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Klassiko",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={unbounded.className}>
      <head>
        <meta name="apple-mobile-web-app-title" content="Klassiko" />
      </head>
      <body className={`unbounded.className antialiased`}>
        <TanstackProvider>
          <UserProvider>{children}</UserProvider>
        </TanstackProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
